# Generated by Django 4.2.15 on 2024-08-13 11:12

from django.db import migrations, models
import laptop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=laptop.models.image_upload)),
            ],
        ),
    ]
