# Generated by Django 4.2.15 on 2024-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='price2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
