# Generated by Django 4.2.15 on 2024-09-20 19:52

from django.db import migrations, models
import django.db.models.deletion
import laptop.models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_laptop_price_laptop_price2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_accessoryl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=laptop.models.image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Category_accessorym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=laptop.models.image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Category_laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=laptop.models.image_upload)),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='description2',
            field=models.TextField(default=1, max_length=4000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Accessorym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('description1', models.TextField(max_length=4000)),
                ('image', models.ImageField(upload_to=laptop.models.image_upload)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.category_accessorym')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoryl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('description1', models.TextField(max_length=4000)),
                ('image', models.ImageField(upload_to=laptop.models.image_upload)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.category_accessoryl')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laptop.category_laptop'),
            preserve_default=False,
        ),
    ]
