# Generated by Django 4.2.15 on 2024-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0008_category_remove_category_accessoryl_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_accessorym',
            name='name2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
