# Generated by Django 4.2.15 on 2024-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0010_remove_product_description1'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryl',
            name='description2',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessorym',
            name='description2',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
