# Generated by Django 4.2.15 on 2024-10-09 12:49

from django.db import migrations, models
import laptop.models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0011_accessoryl_description2_accessorym_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image1',
            field=models.ImageField(default='', upload_to=laptop.models.image_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='image2',
            field=models.ImageField(default='', upload_to=laptop.models.image_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='image3',
            field=models.ImageField(default='', upload_to=laptop.models.image_upload),
            preserve_default=False,
        ),
    ]
